### ISSUE TITLE
Add post-run script execution capability

### ISSUE THREAD

**Issue by probinso** [GaloisInc/ppaml-eval-tools#15]
We already have pre-scripts as `galois.sh` it would be nice to have post run script as well, this is evidenced by the [run output validation](https://github.com/GaloisInc/ppaml-cp5/blob/master/artifacts/validate_results.hs) problem found in challenge problem 5

**Comment by mhuesch** [comment]
I suggest changing `galois.sh` to `pre.sh`, and then adding `post.sh` for this ticket.

**Comment by mhuesch** [comment]
Perhaps `pre_process.sh` and `post_process.sh` are the most descriptive.
